export enum BuiltInToolNames {
  ReadFile = "read_file",
  ReadFileRange = "read_file_range",
  EditExistingFile = "edit_existing_file",
  SingleFindAndReplace = "single_find_and_replace",
  MultiEdit = "multi_edit",
  ReadCurrentlyOpenFile = "read_currently_open_file",
  CreateNewFile = "create_new_file",
  RunTerminalCommand = "run_terminal_command",
  GrepSearch = "grep_search",
  FileGlobSearch = "file_glob_search",
  SearchWeb = "search_web",
  ViewDiff = "view_diff",
  LSTool = "ls",
  CreateRuleBlock = "create_rule_block",
  RequestRule = "request_rule",
  FetchUrlContent = "fetch_url_content",
  CodebaseTool = "codebase",
  BrowserAction = "browser_action",

  // excluded from allTools for now
  ViewRepoMap = "view_repo_map",
  ViewSubdirectory = "view_subdirectory",
  // code added
  FetchUrlChunk = "fetch_url_chunk",
  JiraGetStatus = "jira_getJiraStatus",
  JiraGetAssignee = "jira_getJiraAssignee",
  JiraSearchIssues = "jira_searchJiraIssues",
  JiraTransitionIssue = "jira_transitionJiraIssue",
  JiraAddWorklog = "jira_addWorklog",
  JiraAddComment = "jira_addComment",
  JiraAssignUser = "jira_assignUser",
  JiraGetLastWorklog = "jira_getLastWorklog",
  JiraGetRequirement = "jira_getJiraRequirement",
  JiraGetDescriptionText = "jira_getJiraDescriptionText",
  JiraSetDescriptionText = "jira_setJiraDescriptionText",
  JiraGetLabels = "jira_getJiraLabels",
  JiraSetLabels = "jira_setJiraLabels",
  JiraSetActivityType = "jira_setJiraActivityType",
  JiraCreateEpic = "jira_createEpic",
  JiraCreateFeature = "jira_createFeature",
  JiraCreateStory = "jira_createStory",
  JiraCreateSubtask = "jira_createSubtask",
  JiraSearchWithJql = "jira_searchJiraIssuesWithJql",
  JiraSetDependency = "jira_setJiraDependency",
  JiraGetIssueAttachments = "jira_getIssueAttachments",
  JiraFindSubtasksByActivityType = "jira_findSubtasksByActivityType",
  JiraAddAttachment = "jira_addAttachment",
  JiraGetDueDate = "jira_getDueDate",
  JiraSetDueDate = "jira_setDueDate",
  JiraGetPlannedStartDate = "jira_getPlannedStartDate",
  JiraSetPlannedStartDate = "jira_setPlannedStartDate",
  JiraGetPlannedEndDate = "jira_getPlannedEndDate",
  JiraSetPlannedEndDate = "jira_setPlannedEndDate",
  JiraGetAcceptanceCriteria = "jira_getAcceptanceCriteria",
  JiraSetAcceptanceCriteria = "jira_setAcceptanceCriteria",
  JiraGetFixVersions = "jira_getFixVersionsForJiraIssue",
  JiraGetProjectVersions = "jira_getProjectVersions",
  JiraSetFixVersions = "jira_setFixVersionsForJiraIssue",
  JiraMarkStartOfActivity = "jira_markStartOfActivity",
  JiraMarkActivityCompleted = "jira_markActivityCompleted",

  // Confluence tools
  ConfluenceSearchCQL = "confluence_searchCQL",
  ConfluenceListSpaces = "confluence_listSpaces",
  ConfluenceGetSpaceDetails = "confluence_getSpaceDetails",
  ConfluenceListPages = "confluence_listPages",
  ConfluenceGetPageDetails = "confluence_getPageDetails",
  ConfluenceGetPageContent = "confluence_getPageContent",
  ConfluenceCreatePage = "confluence_createPage",
  ConfluenceAddDiagram = "confluence_addDiagram",
  ConfluenceModifyPageContent = "confluence_modifyPageContent",
  ConfluenceAddPageLabel = "confluence_addPageLabel",

  // ServiceNow tools
  ServiceNowCreateIncident = "servicenow_create_incident",
  ServiceNowUpdateIncident = "servicenow_update_incident",
  ServiceNowAddComment = "servicenow_add_comment",
  ServiceNowResolveIncident = "servicenow_resolve_incident",
  ServiceNowListIncidents = "servicenow_list_incidents",
  ServiceNowGetIncident = "servicenow_get_incident",
  ServiceNowListCatalogItems = "servicenow_list_catalog_items",
  ServiceNowGetCatalogItem = "servicenow_get_catalog_item",
  ServiceNowListCatalogCategories = "servicenow_list_catalog_categories",
  ServiceNowCreateCatalogCategory = "servicenow_create_catalog_category",
  ServiceNowUpdateCatalogCategory = "servicenow_update_catalog_category",
  ServiceNowMoveCatalogItems = "servicenow_move_catalog_items",
  ServiceNowCreateCatalogItemVariable = "servicenow_create_catalog_item_variable",
  ServiceNowListCatalogItemVariables = "servicenow_list_catalog_item_variables",
  ServiceNowUpdateCatalogItemVariable = "servicenow_update_catalog_item_variable",
  ServiceNowListCatalogs = "servicenow_list_catalogs",
  ServiceNowCreateChangeRequest = "servicenow_create_change_request",
  ServiceNowUpdateChangeRequest = "servicenow_update_change_request",
  ServiceNowListChangeRequests = "servicenow_list_change_requests",
  ServiceNowGetChangeRequestDetails = "servicenow_get_change_request_details",
  ServiceNowAddChangeTask = "servicenow_add_change_task",
  ServiceNowSubmitChangeForApproval = "servicenow_submit_change_for_approval",
  ServiceNowApproveChange = "servicenow_approve_change",
  ServiceNowRejectChange = "servicenow_reject_change",
  ServiceNowCreateTask = "servicenow_create_task",
  ServiceNowUpdateTask = "servicenow_update_task",
  ServiceNowGetTask = "servicenow_get_task",
  ServiceNowListTasks = "servicenow_list_tasks",
  ServiceNowCreateProblemTask = "servicenow_create_problem_task",
  ServiceNowUpdateProblemTask = "servicenow_update_problem_task",
  ServiceNowGetProblemTask = "servicenow_get_problem_task",
  ServiceNowListProblemTasks = "servicenow_list_problem_tasks",
  ServiceNowCreateScTask = "servicenow_create_sc_task",
  ServiceNowUpdateScTask = "servicenow_update_sc_task",
  ServiceNowGetScTask = "servicenow_get_sc_task",
  ServiceNowListScTasks = "servicenow_list_sc_tasks",
  ServiceNowListKbArticles = "servicenow_list_kb_articles",
  ServiceNowGetKbArticle = "servicenow_get_kb_article",
  ServiceNowListKbBases = "servicenow_list_kb_bases",
  ServiceNowListKbCategories = "servicenow_list_kb_categories",
  ServiceNowListKbTopics = "servicenow_list_kb_topics",

  ExtractEntities = "extract_entities",
  PlantumlBuilder = "plantuml_builder",

  // Parsing utilities
  ParsePdf = "parse_pdf",
  ParseExcel = "parse_excel",
  ParseDocx = "parse_docx",
  OssVulnerabilityScan = "oss_vulnerability_scan",
}

export const BUILT_IN_GROUP_NAME = "Built-In";

export const CLIENT_TOOLS_IMPLS = [
  BuiltInToolNames.EditExistingFile,
  BuiltInToolNames.SingleFindAndReplace,
  BuiltInToolNames.MultiEdit,
];
