export enum BuiltInToolNames {
  ReadFile = "read_file",
  ReadFileRange = "read_file_range",
  EditExistingFile = "edit_existing_file",
  SingleFindAndReplace = "single_find_and_replace",
  MultiEdit = "multi_edit",
  ReadCurrentlyOpenFile = "read_currently_open_file",
  CreateNewFile = "create_new_file",
  RunTerminalCommand = "run_terminal_command",
  GrepSearch = "grep_search",
  FileGlobSearch = "file_glob_search",
  SearchWeb = "search_web",
  ViewDiff = "view_diff",
  LSTool = "ls",
  CreateRuleBlock = "create_rule_block",
  RequestRule = "request_rule",
  FetchUrlContent = "fetch_url_content",
  CodebaseTool = "codebase",
  BrowserAction = "browser_action",

  // excluded from allTools for now
  ViewRepoMap = "view_repo_map",
  ViewSubdirectory = "view_subdirectory",
  // code added
  FetchUrlChunk = "fetch_url_chunk",
  JiraGetStatus = "jira_getJiraStatus",
  JiraGetAssignee = "jira_getJiraAssignee",
  JiraSearchIssues = "jira_searchJiraIssues",
  JiraTransitionIssue = "jira_transitionJiraIssue",
  JiraAddWorklog = "jira_addWorklog",
  JiraAddComment = "jira_addComment",
  JiraAssignUser = "jira_assignUser",
  JiraGetLastWorklog = "jira_getLastWorklog",
  JiraGetRequirement = "jira_getJiraRequirement",
  JiraGetDescriptionText = "jira_getJiraDescriptionText",
  JiraSetDescriptionText = "jira_setJiraDescriptionText",
  JiraGetLabels = "jira_getJiraLabels",
  JiraSetLabels = "jira_setJiraLabels",
  JiraSetActivityType = "jira_setJiraActivityType",
  JiraCreateEpic = "jira_createEpic",
  JiraCreateFeature = "jira_createFeature",
  JiraCreateStory = "jira_createStory",
  JiraCreateSubtask = "jira_createSubtask",
  JiraSearchWithJql = "jira_searchJiraIssuesWithJql",
  JiraSetDependency = "jira_setJiraDependency",
  JiraGetIssueAttachments = "jira_getIssueAttachments",
  JiraFindSubtasksByActivityType = "jira_findSubtasksByActivityType",
  JiraAddAttachment = "jira_addAttachment",
  JiraGetDueDate = "jira_getDueDate",
  JiraSetDueDate = "jira_setDueDate",
  JiraGetPlannedStartDate = "jira_getPlannedStartDate",
  JiraSetPlannedStartDate = "jira_setPlannedStartDate",
  JiraGetPlannedEndDate = "jira_getPlannedEndDate",
  JiraSetPlannedEndDate = "jira_setPlannedEndDate",
  JiraGetAcceptanceCriteria = "jira_getAcceptanceCriteria",
  JiraSetAcceptanceCriteria = "jira_setAcceptanceCriteria",
  JiraGetFixVersions = "jira_getFixVersionsForJiraIssue",
  JiraGetProjectVersions = "jira_getProjectVersions",
  JiraSetFixVersions = "jira_setFixVersionsForJiraIssue",
  JiraMarkStartOfActivity = "jira_markStartOfActivity",
  JiraMarkActivityCompleted = "jira_markActivityCompleted",
}

export const BUILT_IN_GROUP_NAME = "Built-In";

export const CLIENT_TOOLS_IMPLS = [
  BuiltInToolNames.EditExistingFile,
  BuiltInToolNames.SingleFindAndReplace,
  BuiltInToolNames.MultiEdit,
];
